### ISSUE TITLE
dynamic module not binary compatible

### ISSUE THREAD

**Issue by bodonkerhoderos** [Kong/lua-resty-lmdb#20]
(real quick thank you all for making this. i am trying to use it in a hobby project)

I incorporated the changes from #18 to the latest commit and attempted to build it as a dynamic module to drop into my existing nginx install from apt. after some fiddling i got it to build but nginx complains that the resulting .so was not binary compatible.

i'm using the same configuration options as shown in `nginx -V` which indicates it is built with the `--with-compat` flag and i have nginx source cloned from the official git mirror with the same version tag checked out (1.18.0) and i have done a `make clean` in both the nginx source directory and the lmdb submodule here before building with `make modules`

the only thing i can think of that is different is that i used a different version of openssl by accident and removed the the unnecesary other dynamic modules and the gzip and pcre modules because i didnt think them relevant. but by this point i realized i was out of my depth and aimlessly grasping.

any suggestions for how to proceed? or is this kind of question a bit out of scope?

**Comment by dndx** [comment]
We currently do not have plan for dynamic modules for our use cases.
