### ISSUE TITLE
resty/lmdb/transaction.lua:245 lib/libluajit-5.1.so.2: undefined symbol: ngx_lua_resty_lmdb_ffi_execute

### ISSUE THREAD

**Issue by zhaoshoucheng** [Kong/lua-resty-lmdb#21]
I want to use lmdb in my project
I make the lmdb and get liblmdb.so
I use lmdb.lua and transaction.lua in my project
but get the err undefined symbol: ngx_lua_resty_lmdb_ffi_execute
I think this may be my luajit problem, but how can I solve it

nginx version: openresty/1.19.3.1rc0

./configure --prefix=/data/pkg/openresty --user=nginx --group=nginx --with-pcre-jit --with-http_v2_module --with-http_sub_module --with-http_realip_module --with-http_stub_status_module --with-luajit --add-module=$otherbundles/nginx-sticky-module-ng  --add-module=$otherbundles/nginx_upstream_check_module --add-module=$otherbundles/ngx_stream_upstream_check_module --with-openssl=$otherbundles/openssl/$OPENSSL_VERSION --with-pcre=$otherbundles/pcre/pcre-8.40 --with-zlib=$otherbundles/zlib/zlib-1.2.10

**Comment by zhaoshoucheng** [comment]
> You should use `--add-module=/path/to/lua-resty-lmdb`.

But I have a new problem

objs/addon/src/ngx_lua_resty_lmdb_module.o: In function `ngx_lua_resty_lmdb_init_worker':
/data/lua-resty-lmdb-master/src/ngx_lua_resty_lmdb_module.c:296: undefined reference to `mdb_env_set_encrypt'

definition not found in source code

**Comment by chronolaw** [comment]
Perhaps you missed submodule `lmdb`, try:
`git clone git@github.com:Kong/lua-resty-lmdb.git  --recursive`.

**Comment by zhaoshoucheng** [comment]
ok ,i get the wrong branch of lmdb source code

**Comment by zhaoshoucheng** [comment]
> Perhaps you missed submodule `lmdb`, try: `git clone git@github.com:Kong/lua-resty-lmdb.git --recursive`.

Whether there is a demo to use Apis or kong source code link
db? Do I need to initialize through the C API
My understanding is that if I do not set db, I will use _defelut, but an error is reported

lmdb err err: unable to open DB for access: no LMDB environment defined

Maybe I don't understand deeply,forgive me, thank you

**Comment by chronolaw** [comment]
You should use nginx directive to config lmdb's path, like:

```
lmdb_environment_path xxx.lmdb;
lmdb_map_size         128m;
```

**Comment by zhaoshoucheng** [comment]
it work
i config the nginx directive  lmdb_environment_path and lmdb_map_size on the nginx.conf
It's really convenient to use， thank you very much
