### ISSUE TITLE
lua cannot read lmdb create by python or c

### ISSUE THREAD

**Issue by wzyforgit** [Kong/lua-resty-lmdb#55]
I create a lmdb by python(`pip3 install lmdb`), set key and value, when I use lua to read it by the key, I get a nil data.
The python edition lmdb can be used by c edition(just use the c language to read it).

If I use lua in nginx to set key and value, the lmdb can read by lua.
Python and c cannot read it by the key with lua edition.

My key and value just like:
"key": "value"
"qwer": "1234"
Very simple strings

more: 
python: 3.6.8
lua-resty-lmdb: v1.4.2
nginx: openresty-1.25.3.1

**Comment by StarlightIbuki** [comment]
Please ensure you are using the same version of LMDB as it does not maintain compatibility between versions.
Please note that due to the limitation of LMDB, keys cannot have a length greater than 1024. Kong's workaround is to hash the key when it exceeds the limit.

**Comment by StarlightIbuki** [comment]
If you have any further consideration please feel free to reopen the issue.

**Comment by StarlightIbuki** [comment]
Plus the library writes to a specific namespace, so you could not get anything from the default namespace.
